// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FormProduct() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"form\" method=\"POST\" action=\"/products\" id=\"create-product-form\"><div class=\"form-group\"><div class=\"option-texts\"><label for=\"p-nombre\">Nombre del Producto</label> <input type=\"text\" id=\"p-nombre\" name=\"nombre_producto\" placeholder=\"Ingrese el nombre del producto\"></div><div class=\"option-number\"><label for=\"p-precio\">$</label> <input type=\"number\" id=\"p-precio\" name=\"precio\" min=\"0\" placeholder=\"100.00\"></div></div><div class=\"form-group\"><div class=\"option-texts\"><label for=\"p-categoria\">Categoría</label> <select id=\"p-categoria\" name=\"categoria\"><option value=\"\">Seleccione una categoría</option> <option value=\"pc\">PC de escritorio</option> <option value=\"laptop\">Laptops</option> <option value=\"perifericos\">Periféricos</option> <option value=\"componentes\">Componentes</option> <option value=\"otros\">Otros</option></select></div><div class=\"option-number\"><label for=\"p-stock\">Cantidad</label> <input type=\"number\" name=\"stock\" id=\"p-stock\" min=\"1\" placeholder=\"100\"></div></div><div class=\"option-texts\"><label for=\"p-imagen\">URL de la imagen</label> <input type=\"text\" id=\"p-imagen\" name=\"imagen\" placeholder=\"Ingrese la URL de la imagen\"></div><div class=\"option-texts\"><label for=\"p-descripcion\">Descripción</label> <textarea id=\"p-descripcion\" name=\"descripcion\" rows=\"3\" placeholder=\"Ingrese la descripción del producto\"></textarea></div><button type=\"submit\" class=\"btn\" hx-post=\"/products\" hx-target=\"#product-list\">Agregar Producto</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
