// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Carrito struct {
	IDItem        int32        `json:"id_item"`
	IDUsuario     int32        `json:"id_usuario"`
	IDProducto    int32        `json:"id_producto"`
	Cantidad      int32        `json:"cantidad"`
	FechaAgregado sql.NullTime `json:"fecha_agregado"`
}

type Producto struct {
	IDProducto     int32  `json:"id_producto"`
	NombreProducto string `json:"nombre_producto"`
	Descripcion    string `json:"descripcion"`
	Precio         string `json:"precio"`
	Stock          int32  `json:"stock"`
	Categoria      string `json:"categoria"`
	Imagen         string `json:"imagen"`
}

type Usuario struct {
	IDUsuario     int32  `json:"id_usuario"`
	NombreUsuario string `json:"nombre_usuario"`
	Email         string `json:"email"`
}

type Ventum struct {
	IDVenta    int32        `json:"id_venta"`
	IDProducto int32        `json:"id_producto"`
	IDUsuario  int32        `json:"id_usuario"`
	Cantidad   int32        `json:"cantidad"`
	Total      string       `json:"total"`
	Fecha      sql.NullTime `json:"fecha"`
}
