// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Producto struct {
	ID          int32          `json:"id"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	Precio      string         `json:"precio"`
	Stock       int32          `json:"stock"`
	Categoria   sql.NullString `json:"categoria"`
}

type Usuario struct {
	IDUsuario int32  `json:"id_usuario"`
	Nombre    string `json:"nombre"`
	Email     string `json:"email"`
}

type Ventum struct {
	IDVenta    int32        `json:"id_venta"`
	IDProducto int32        `json:"id_producto"`
	IDUsuario  int32        `json:"id_usuario"`
	Cantidad   int32        `json:"cantidad"`
	Precio     string       `json:"precio"`
	Fecha      sql.NullTime `json:"fecha"`
}
