// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createProd = `-- name: CreateProd :one
INSERT INTO producto (nombre_producto, descripcion, precio, stock, categoria, imagen) VALUES ($1,$2, $3, $4, $5, $6) RETURNING id_producto, nombre_producto, descripcion, precio, stock, categoria, imagen
`

type CreateProdParams struct {
	NombreProducto string `json:"nombre_producto"`
	Descripcion    string `json:"descripcion"`
	Precio         string `json:"precio"`
	Stock          int32  `json:"stock"`
	Categoria      string `json:"categoria"`
	Imagen         string `json:"imagen"`
}

func (q *Queries) CreateProd(ctx context.Context, arg CreateProdParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProd,
		arg.NombreProducto,
		arg.Descripcion,
		arg.Precio,
		arg.Stock,
		arg.Categoria,
		arg.Imagen,
	)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.NombreProducto,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
		&i.Categoria,
		&i.Imagen,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO usuario (nombre_usuario, email) VALUES ($1, $2) RETURNING id_usuario, nombre_usuario, email
`

type CreateUserParams struct {
	NombreUsuario string `json:"nombre_usuario"`
	Email         string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.NombreUsuario, arg.Email)
	var i Usuario
	err := row.Scan(&i.IDUsuario, &i.NombreUsuario, &i.Email)
	return i, err
}

const createVenta = `-- name: CreateVenta :one
INSERT INTO venta (id_producto,id_usuario, cantidad, total, fecha) VALUES ($1, $2, $3, $4, $5) RETURNING id_venta, id_producto, id_usuario, cantidad, total, fecha
`

type CreateVentaParams struct {
	IDProducto int32        `json:"id_producto"`
	IDUsuario  int32        `json:"id_usuario"`
	Cantidad   int32        `json:"cantidad"`
	Total      string       `json:"total"`
	Fecha      string `json:"fecha"`
}

func (q *Queries) CreateVenta(ctx context.Context, arg CreateVentaParams) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, createVenta,
		arg.IDProducto,
		arg.IDUsuario,
		arg.Cantidad,
		arg.Total,
		arg.Fecha,
	)
	var i Ventum
	err := row.Scan(
		&i.IDVenta,
		&i.IDProducto,
		&i.IDUsuario,
		&i.Cantidad,
		&i.Total,
		&i.Fecha,
	)
	return i, err
}

const deleteProd = `-- name: DeleteProd :exec
DELETE FROM producto WHERE id_producto = $1
`

func (q *Queries) DeleteProd(ctx context.Context, idProducto int32) error {
	_, err := q.db.ExecContext(ctx, deleteProd, idProducto)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM usuario WHERE id_usuario = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, idUsuario)
	return err
}

const deleteVenta = `-- name: DeleteVenta :exec
DELETE FROM venta WHERE id_venta = $1
`

func (q *Queries) DeleteVenta(ctx context.Context, idVenta int32) error {
	_, err := q.db.ExecContext(ctx, deleteVenta, idVenta)
	return err
}

const getProd = `-- name: GetProd :one
SELECT id_producto, nombre_producto, descripcion, precio, stock, categoria, imagen FROM producto WHERE id_producto = $1
`

func (q *Queries) GetProd(ctx context.Context, idProducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProd, idProducto)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.NombreProducto,
		&i.Descripcion,
		&i.Precio,
		&i.Stock,
		&i.Categoria,
		&i.Imagen,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT nombre_usuario, email FROM usuario WHERE id_usuario = $1
`

type GetUserRow struct {
	NombreUsuario string `json:"nombre_usuario"`
	Email         string `json:"email"`
}

func (q *Queries) GetUser(ctx context.Context, idUsuario int32) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, idUsuario)
	var i GetUserRow
	err := row.Scan(&i.NombreUsuario, &i.Email)
	return i, err
}

const getVenta = `-- name: GetVenta :one
SELECT id_venta, id_producto, id_usuario, cantidad, total, fecha FROM venta WHERE id_venta = $1
`

func (q *Queries) GetVenta(ctx context.Context, idVenta int32) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, getVenta, idVenta)
	var i Ventum
	err := row.Scan(
		&i.IDVenta,
		&i.IDProducto,
		&i.IDUsuario,
		&i.Cantidad,
		&i.Total,
		&i.Fecha,
	)
	return i, err
}

const getVenta_usuario = `-- name: GetVenta_usuario :one
SELECT id_venta, id_producto, id_usuario, cantidad, total, fecha FROM venta WHERE id_usuario = $1
`

func (q *Queries) GetVenta_usuario(ctx context.Context, idUsuario int32) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, getVenta_usuario, idUsuario)
	var i Ventum
	err := row.Scan(
		&i.IDVenta,
		&i.IDProducto,
		&i.IDUsuario,
		&i.Cantidad,
		&i.Total,
		&i.Fecha,
	)
	return i, err
}

const listProd = `-- name: ListProd :many
SELECT id_producto, nombre_producto, descripcion, precio, stock, categoria, imagen FROM producto ORDER BY nombre_producto
`

func (q *Queries) ListProd(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.NombreProducto,
			&i.Descripcion,
			&i.Precio,
			&i.Stock,
			&i.Categoria,
			&i.Imagen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByPriceAsc = `-- name: ListProductsByPriceAsc :many
SELECT id_producto, nombre_producto, descripcion, precio, stock, categoria, imagen FROM producto ORDER BY precio ASC
`

func (q *Queries) ListProductsByPriceAsc(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByPriceAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.NombreProducto,
			&i.Descripcion,
			&i.Precio,
			&i.Stock,
			&i.Categoria,
			&i.Imagen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByPriceDesc = `-- name: ListProductsByPriceDesc :many
SELECT id_producto, nombre_producto, descripcion, precio, stock, categoria, imagen FROM producto ORDER BY precio DESC
`

func (q *Queries) ListProductsByPriceDesc(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByPriceDesc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.NombreProducto,
			&i.Descripcion,
			&i.Precio,
			&i.Stock,
			&i.Categoria,
			&i.Imagen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id_usuario, nombre_usuario, email FROM usuario ORDER BY nombre_usuario
`

func (q *Queries) ListUsers(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(&i.IDUsuario, &i.NombreUsuario, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentas = `-- name: ListVentas :many
SELECT id_venta, id_producto, id_usuario, cantidad, total, fecha FROM venta ORDER BY fecha
`

func (q *Queries) ListVentas(ctx context.Context) ([]Ventum, error) {
	rows, err := q.db.QueryContext(ctx, listVentas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ventum
	for rows.Next() {
		var i Ventum
		if err := rows.Scan(
			&i.IDVenta,
			&i.IDProducto,
			&i.IDUsuario,
			&i.Cantidad,
			&i.Total,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentasUsuario = `-- name: ListVentasUsuario :many
SELECT id_venta, id_producto, id_usuario, cantidad, total, fecha FROM venta WHERE id_usuario = $1
`

func (q *Queries) ListVentasUsuario(ctx context.Context, idUsuario int32) ([]Ventum, error) {
	rows, err := q.db.QueryContext(ctx, listVentasUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ventum
	for rows.Next() {
		var i Ventum
		if err := rows.Scan(
			&i.IDVenta,
			&i.IDProducto,
			&i.IDUsuario,
			&i.Cantidad,
			&i.Total,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducto = `-- name: UpdateProducto :exec
UPDATE producto SET nombre_producto = $2, descripcion = $3, stock = $4, precio = $5, categoria = $6, imagen = $7 WHERE id_producto = $1
`

type UpdateProductoParams struct {
	IDProducto     int32  `json:"id_producto"`
	NombreProducto string `json:"nombre_producto"`
	Descripcion    string `json:"descripcion"`
	Stock          int32  `json:"stock"`
	Precio         string `json:"precio"`
	Categoria      string `json:"categoria"`
	Imagen         string `json:"imagen"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateProducto,
		arg.IDProducto,
		arg.NombreProducto,
		arg.Descripcion,
		arg.Stock,
		arg.Precio,
		arg.Categoria,
		arg.Imagen,
	)
	return err
}

const updateProductoPrecio = `-- name: UpdateProductoPrecio :exec
UPDATE producto SET precio = $2 WHERE id_producto = $1
`

type UpdateProductoPrecioParams struct {
	IDProducto int32  `json:"id_producto"`
	Precio     string `json:"precio"`
}

func (q *Queries) UpdateProductoPrecio(ctx context.Context, arg UpdateProductoPrecioParams) error {
	_, err := q.db.ExecContext(ctx, updateProductoPrecio, arg.IDProducto, arg.Precio)
	return err
}

const updateProductoStock = `-- name: UpdateProductoStock :exec
UPDATE producto SET stock = $2 WHERE id_producto = $1
`

type UpdateProductoStockParams struct {
	IDProducto int32 `json:"id_producto"`
	Stock      int32 `json:"stock"`
}

func (q *Queries) UpdateProductoStock(ctx context.Context, arg UpdateProductoStockParams) error {
	_, err := q.db.ExecContext(ctx, updateProductoStock, arg.IDProducto, arg.Stock)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE usuario SET nombre_usuario = $2, email = $3 WHERE id_usuario = $1
`

type UpdateUserParams struct {
	IDUsuario     int32  `json:"id_usuario"`
	NombreUsuario string `json:"nombre_usuario"`
	Email         string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.IDUsuario, arg.NombreUsuario, arg.Email)
	return err
}

const updateVenta = `-- name: UpdateVenta :exec
UPDATE venta SET cantidad = $2, total = $3, fecha = $4 WHERE id_venta = $1
`

type UpdateVentaParams struct {
	IDVenta  int32        `json:"id_venta"`
	Cantidad int32        `json:"cantidad"`
	Total    string       `json:"total"`
	Fecha    string       `json:"fecha"`
}

func (q *Queries) UpdateVenta(ctx context.Context, arg UpdateVentaParams) error {
	_, err := q.db.ExecContext(ctx, updateVenta,
		arg.IDVenta,
		arg.Cantidad,
		arg.Total,
		arg.Fecha,
	)
	return err
}
